import type { Metadata } from "next";
import {Outfit} from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

const outfit = Outfit({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Hablu Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={outfit.className}>
        <div className="flex flex-col min-h-screen w-11/12 max-w-screen-xl mx-auto">
          <Navbar></Navbar>
          <main className="flex-grow">
            {children}
          </main>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
